repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-ast
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/astral-sh/uv-pre-commit
    # uv version
    rev: 0.8.8
    hooks:
    -   id: uv-lock
    -   id: uv-export

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.9
    hooks:
    # Run the linter.
    -   id: ruff-check
    # Run the formatter.
    -   id: ruff-format

-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.403
    hooks:
    -   id: pyright